import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#faf5ff',
    },
    scrollContent: {
      flexGrow: 1,
    },
    content: {
      flex: 1,
      padding: 20,
      paddingTop: 60,
    },
    heroSection: {
      alignItems: 'center',
      marginBottom: 40,
    },
    logo: {
      width: 80,
      height: 120,
    },
    titleContainer: {
      minHeight: 80,
      marginBottom: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    typewriterText: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#9333ea',
      textAlign: 'center',
      lineHeight: 36,
      maxWidth: '100%',
    },
    cursor: {
      color: '#9333ea',
      opacity: 0.7,
    },
    subtitle: {
      fontSize: 22,
      fontWeight: '600',
      color: '#1f2937',
      marginBottom: 12,
      textAlign: 'center',
    },
    description: {
      fontSize: 16,
      color: '#6b7280',
      textAlign: 'center',
      marginBottom: 32,
      paddingHorizontal: 20,
      lineHeight: 24,
    },
    googleButton: {
      width: '100%',
      maxWidth: 320,
      borderRadius: 30,
      overflow: 'hidden',
      marginBottom: 15,
      shadowColor: '#9333ea',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    buttonDisabled: {
      opacity: 0.6,
    },
    buttonGradient: {
      paddingVertical: 18,
      paddingHorizontal: 32,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    buttonText: {
      color: '#ffffff',
      fontSize: 18,
      fontWeight: '600',
      marginRight: 8,
    },
    buttonIcon: {
      marginLeft: 4,
    },
    phoneButton: {
      width: '100%',
      maxWidth: 320,
      paddingVertical: 16,
      paddingHorizontal: 30,
      borderRadius: 25,
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      borderWidth: 2,
      borderColor: '#9333ea',
      alignItems: 'center',
      marginBottom: 20,
    },
    phoneButtonText: {
      color: '#9333ea',
      fontSize: 18,
      fontWeight: '600',
    },
    errorContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fee2e2',
      borderRadius: 12,
      padding: 12,
      marginTop: 10,
      maxWidth: 320,
    },
    errorText: {
      color: '#dc2626',
      fontSize: 14,
      marginLeft: 8,
      flex: 1,
    },
    featuresSection: {
      marginTop: 20,
      paddingBottom: 40,
    },
    featuresTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#9333ea',
      textAlign: 'center',
      marginBottom: 8,
    },
    featuresSubtitle: {
      fontSize: 16,
      color: '#6b7280',
      textAlign: 'center',
      marginBottom: 24,
      paddingHorizontal: 20,
    },
    featuresGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
    },
    featureCard: {
      width: '48%',
      backgroundColor: 'rgba(255, 255, 255, 0.87)',
      borderRadius: 20,
      padding: 16,
      marginBottom: 16,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    featureIconContainer: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    featureTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#1f2937',
      marginBottom: 6,
      textAlign: 'center',
    },
    featureDescription: {
      fontSize: 12,
      color: '#6b7280',
      textAlign: 'center',
      lineHeight: 18,
    },
  });
  